- id: Home_Assistant_Check_State
  alias: Home Assistant check state
  description: Home Assistant проверка состояния системы
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /state
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Температура процессора {{ states('sensor.processor_temperature') }}
        °С Загруженность процессора {{ states('sensor.processor_use_percent') }} %
        Оперативной памяти свободно {{ states('sensor.memory_free') }} Мб Оперативной
        памяти использовано {{ states('sensor.memory_use') }} Мб Места на диске занято
        {{ states('sensor.disk_use') }} Гб Места на диске свободно {{ states('sensor.disk_free_home')
        }} Гб
  - service: notify.dima_notifer
    data:
      message: Температура процессора {{ states('sensor.processor_temperature') }}
        °С     Загруженность процессора {{ states('sensor.processor_use_percent')
        }} %     Оперативной памяти свободно {{ states('sensor.memory_free') }} Мб     Оперативной
        памяти использовано {{ states('sensor.memory_use') }} Мб Места     на диске
        занято {{ states('sensor.disk_use') }} Гб Места на диске свободно     {{ states('sensor.disk_free_home')
        }} Гб
  mode: single
- id: '1614508760199'
  alias: Состояние батареек беспроводных устр - в
  description: ''
  trigger:
  - platform: numeric_state
    below: '10'
    entity_id: sensor.temperature_indor_battery
  - platform: numeric_state
    below: '10'
    entity_id: sensor.temperaure_outdoor_battery
  - platform: numeric_state
    entity_id: sensor.button_bed_battery
    below: '10'
  - platform: numeric_state
    entity_id: sensor.button_table_battery
    below: '10'
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: 🔋Заряд батареи одного из устройств меньше 10%
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: 'Заряд батареи:'
    message: 🔋Заряд батареи одного из устройств меньше 10%
  mode: single
- id: '1615325207808'
  alias: Обновитесь, батенька!
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: sensor.hacs
    from: '0'
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: 🎉Найдено обновление Cистемы/Hacs. Рекомендуется обновиться.
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: 'Обновление:'
    message: 🎉Найдено обновление Cистемы/Hacs. Рекомендуется обновиться.
  mode: single
- id: '1615816717645'
  alias: 'Выключить все: устройства'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.vykliuchit_vsio_ustroistva
    from: 'off'
    to: 'on'
  - platform: device
    domain: mqtt
    device_id: a865db44c9b617f8d4cf752b49b51601
    type: action
    subtype: hold
    discovery_id: 0x00158d0005bdb096 action_hold
  - platform: time
    at: 09:00
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: hold
    discovery_id: 0x00158d0005bdd1ef action_hold
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.vykliuchit_vsio_ustroistva
  - service: switch.turn_off
    target:
      entity_id:
      - switch.212a01_5448e67c5bf5
      - switch.212a01_5448e67c5d70
      - switch.212a01_5448e6e68e77
      - switch.212a01_5448e6d89786
  - service: light.turn_off
    target:
      entity_id: light.wled
  mode: single
- id: '1615816863874'
  alias: 'Выключить всё: сценарии'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.vykliuchit_vsio_stsenarii
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.vykliuchit_vsio_stsenarii
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.uvlazhnitel
  mode: single
- id: '1616496969636'
  alias: Увлажнитель таймер
  description: Включегие увлажнителя по кнопке, выключение по таймеру
  trigger:
  - platform: state
    entity_id: input_boolean.humtimer
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 9ac9695704437aed2da93c6a211670ea
    entity_id: switch.212a01_5448e67c5d70
    domain: switch
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.do_vykliucheniia
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 9ac9695704437aed2da93c6a211670ea
    entity_id: switch.212a01_5448e67c5d70
    domain: switch
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.humtimer
  mode: single
- id: '1616618297192'
  alias: Проверка питания
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.rpi_power_status
    from: 'off'
    to: 'on'
  condition: []
  action:
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: Сервер
    message: Качество подаваемого питания изменилось
  mode: single
- id: '1617642797212'
  alias: Свет на столе
  description: Управление светом на столе
  trigger:
  - platform: device
    domain: mqtt
    device_id: a865db44c9b617f8d4cf752b49b51601
    type: click
    subtype: single
    discovery_id: 0x00158d0005bdb096 click_single
  condition: []
  action:
  - type: toggle
    device_id: cdc3f740f9cf31647340eb1aaa9e7b47
    entity_id: switch.212a01_5448e6e68e77
    domain: switch
  mode: single
- id: '1617643294294'
  alias: Свет на диване
  description: Управляет светом на диване
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: single
    discovery_id: 0x00158d0005bdd1ef action_single
  - platform: time
    at: 07:00
  - platform: device
    domain: mqtt
    device_id: a865db44c9b617f8d4cf752b49b51601
    type: action
    subtype: quadruple
    discovery_id: 0x00158d0005bdb096 action_quadruple
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.212a01_5448e67c5bf5
  mode: single
- id: '1617653540312'
  alias: Увлажнитель
  description: Управляет увлажнителем
  trigger:
  - platform: numeric_state
    above: '38'
    entity_id: sensor.indoor_sensor_humidity
  - platform: numeric_state
    below: '30'
    entity_id: sensor.indoor_sensor_humidity
  - platform: device
    domain: mqtt
    device_id: a865db44c9b617f8d4cf752b49b51601
    type: click
    subtype: triple
    discovery_id: 0x00158d0005bdb096 click_triple
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.212a01_5448e67c5d70
  mode: single
- id: '1617829237217'
  alias: Ноутбук
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.noutbuk
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.noutbuk
    from: 'off'
    to: 'on'
  - platform: device
    domain: mqtt
    device_id: a865db44c9b617f8d4cf752b49b51601
    type: action
    subtype: many
    discovery_id: 0x00158d0005bdb096 action_many
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.212a01_5448e6d89786
  mode: single
- id: '1618243620450'
  alias: Увлажнитель таймер (Сброс)
  description: Сброс таймера увлажнителя при выключении
  trigger:
  - platform: state
    entity_id: input_boolean.humtimer
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: timer.cancel
    target:
      entity_id: timer.do_vykliucheniia
  - service: switch.turn_off
    target:
      entity_id: switch.212a01_5448e67c5d70
  mode: single
- id: '1618664161298'
  alias: Home Assistant reboot server
  description: Home Assistant перезагрузка сервера
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /reboot
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Перезагрузка сервера...
  - service: hassio.host_reboot
  mode: single
- id: '1618778540079'
  alias: Увлажнитель (выключен)
  description: Меняет статус в input_select
  trigger:
  - platform: state
    entity_id: binary_sensor.humr_status
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.uvlazhnitel
    data:
      option: Выключен
  mode: single
- id: '1618779031571'
  alias: Увлажнитель (воды нет)
  description: Определяет наличие воды в увлажнителе
  trigger:
  - platform: numeric_state
    entity_id: sensor.212a01_5448e67c5d70_power
    above: '5'
    for: 00:01:00
    below: '37'
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.uvlazhnitel
    data:
      option: Воды нет
  - service: switch.turn_off
    target:
      entity_id: switch.212a01_5448e67c5d70
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: 'Увлажнитель:'
    message: 💧Вода закончилась. Необходимо долить.
  mode: single
- id: '1618851164816'
  alias: 'Увлажнитель (включен) '
  description: Определяет наличие воды в увлажнителе
  trigger:
  - platform: state
    entity_id: binary_sensor.humr_status
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.uvlazhnitel
    data:
      option: Работает
  mode: single
- id: '1618906687342'
  alias: Отключение охраны, когда я прихожу домой
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.telefon
    from: 'off'
    to: 'on'
  condition: []
  action:
  - device_id: f0ddec060bc77273c836507d21fba40b
    domain: alarm_control_panel
    entity_id: alarm_control_panel.0x588e81fffedd1b42_alarm
    type: disarm
    code: ''
  mode: single
- id: '1619799271890'
  alias: Увлажнитель (без присмотра)
  description: ''
  trigger:
  - platform: time
    at: '12:00'
  - platform: time
    at: '22:00'
  condition:
  - condition: zone
    entity_id: person.matvey
    zone: zone.dacha
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.212a01_5448e67c5d70
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: Увлажнитель
    message: 'Без присмотра: включен'
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.212a01_5448e67c5d70
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: Увлажнитель
    message: 'Без присмотра: выключен'
  mode: single
- id: '1620928231152'
  alias: Home Assistant reboot overheat
  description: Перезагрузка сервера при перегреве процессора
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    above: '80'
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: 🌡Температура процессора выше 80 °C Текущая температура {{ states('sensor.processor_temperature')
        }}. Перезагрузка хоста...
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: hassio.host_reboot
  mode: single
- id: '1620929932640'
  alias: Home Assistant on boot
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Сервер работает!
  - device_id: b6085fd2dacf8f388c0847f208cd5489
    domain: mobile_app
    type: notify
    title: Сервер работает!
    message: ' Сервер запущен!'
  mode: single
- id: '1621099645067'
  alias: Home Assistant days after instaling
  description: ''
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - service: counter.increment
    target:
      entity_id:
      - counter.total_days_after_installing_ha
      - counter.dnei_s_ochistki_bazy
  mode: single
- id: '1622477091212'
  alias: Светодиодная лента цвет фиолетовый
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: quadruple
    discovery_id: 0x00158d0005bdd1ef action_quadruple
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.lenta_ws2812
    data:
      color_name: violet
  mode: single
- id: '1623399773279'
  alias: Как списать с MI band
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.a10_ringer_mode
    to: silent
  - platform: event
    event_type: telegram_command
    event_data:
      command: /sh
  condition: []
  action:
  - device_id: b6eddb77568ab4e8358a75c40689de20
    domain: mobile_app
    type: notify
    message: electricity-электричество, lead-вести, in-depth study-глубокое изучение,
      electron-электрон, electrical charge-электрич.заряд
    title: '1'
  - device_id: b6eddb77568ab4e8358a75c40689de20
    domain: mobile_app
    type: notify
    message: current-ток,resistance-сопротивление, conduct-проводить, measure-измерять,
      unit of measurement-эд.изм, ampere-aмпер
    title: '2'
  - device_id: b6eddb77568ab4e8358a75c40689de20
    domain: mobile_app
    type: notify
    message: volt-вольт, ohm-ом, watt-ватт, circuit-схема/цепь, copper-медь, wire-провод,
      flow of electricity-эл.ток, oppose-сопротивляться
    title: '3'
  - device_id: b6eddb77568ab4e8358a75c40689de20
    domain: mobile_app
    type: notify
    message: property-св-во, particle-частица, base unit-основная единица
    title: '4'
  - service: notify.dima_notifer
    data:
      title: '1'
      message: electricity-электричество, lead-вести, in-depth study-глубокое изучение,
        electron-электрон, electrical charge-электрич.заряд
  - service: notify.dima_notifer
    data:
      title: '2'
      message: current-ток,resistance-сопротивление, conduct-проводить, measure-измерять,
        unit of measurement-эд.изм, ampere-aмпер
  - service: notify.dima_notifer
    data:
      title: '3'
      message: volt-вольт, ohm-ом, watt-ватт, circuit-схема/цепь, copper-медь, wire-провод,
        flow of electricity-эл.ток, oppose-сопротивляться
  - service: notify.dima_notifer
    data:
      message: property-св-во, particle-частица, base unit-основная единица
      title: '4'
  mode: single
- id: '1630338677733'
  alias: Адресная лента вкл/выкл
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: double
    discovery_id: 0x00158d0005bdd1ef action_double
  - platform: device
    domain: mqtt
    device_id: a865db44c9b617f8d4cf752b49b51601
    type: action
    subtype: double
    discovery_id: 0x00158d0005bdb096 action_double
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.wled
  mode: single
- id: '1630339127639'
  alias: Адресная лента. Режим washing machine
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: triple
    discovery_id: 0x00158d0005bdd1ef action_triple
  condition: []
  action:
  - scene: scene.svetodiodnaia_lenta_rezhim_washing_machine_2
  mode: single
- id: '1630347348453'
  alias: Сжатие базы и создание бэкапа
  description: ''
  trigger:
  - platform: time
    at: 00:01
  condition: []
  action:
  - service: recorder.purge
    data:
      repack: true
      keep_days: 8
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: hassio.snapshot_full
    data:
      name: Backup {{ states('sensor.date_time') }}
  mode: single
- id: '1630518243908'
  alias: Адресная лента. Режим Scan
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: quadruple
    discovery_id: 0x00158d0005bdd1ef action_quadruple
  condition: []
  action:
  - scene: scene.svetodiodnaia_lenta_rezhim_scan
  mode: single
- id: '1632214992942'
  alias: Выключить автоматизации, при покидании зоны дом
  description: ''
  trigger:
  - platform: zone
    entity_id: person.matvey
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: automation.turn_off
    target:
      entity_id:
      - automation.svet_na_divane
      - automation.uvlazhnitel
  mode: single
- id: '1632215169459'
  alias: Включить автоматизации при появлении в зоне дом
  description: ''
  trigger:
  - platform: zone
    entity_id: person.matvey
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: automation.turn_on
    target:
      entity_id:
      - automation.uvlazhnitel
      - automation.svet_na_divane
  mode: single
- id: '1633733317387'
  alias: Адресная лента ночной свет
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5322cc660685143f79b812e21dda7045
    type: action
    subtype: many
    discovery_id: 0x00158d0005bdd1ef action_many
  condition: []
  action:
  - scene: scene.svetodiodnaia_lenta_nochnoi_svet
  mode: single
