
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include_dir_merge_list conf/switches
sensor: !include_dir_merge_list conf/sensors
climate: !include_dir_merge_list conf/climates
#plant: !include conf/plant.yaml

discovery:

homeassistant:
  packages: !include_dir_named conf
  customize: !include customize.yaml
  
panel_iframe:
  mdi:
    title: "MDI"
    icon: mdi:material-design
    url: "https://mdi.bessarabov.com/"

frontend:
  themes: !include_dir_merge_named themes
  
recorder:
  db_url: mysql://homeassistant:homeassistant@core-mariadb/homeassistant?charset=utf8mb4
  purge_keep_days: 15
  exclude:
    domains:
      - automation
      - updater
      - weather
      - hacs
      - zone
    entities:
      - sensor.date
      - sensor.time    
      
history:
  exclude:
    domains:
      - automation
      - updater
      - weather
      - hacs
      - zone
    entities:
      - sensor.date
      - sensor.time
      
logbook:
  exclude:
    domains:
      - automation
      - updater
      - weather
      - hacs
      - zone
    entities:
      - sensor.date
      - sensor.time    

yandex_smart_home:
