sensor: 
 #### Ноут ####   
  - platform: mqtt
    state_topic: "mqtt/comp/state"
    name: "Ноутбук статус"

  - platform: mqtt
    state_topic: "mqtt/comp/battery"
    unit_of_measurement: "%"
    name: "Ноутбук заряд батареи"

  - platform: mqtt
    state_topic: "mqtt/comp/cpu"
    unit_of_measurement: "%"
    name: "Ноутбук загрузка процессора"
    
  - platform: mqtt
    state_topic: "mqtt/comp/memory_use"
    unit_of_measurement: "Мб"
    name: "Ноутбук оперативки занято"
    
  - platform: mqtt
    state_topic: "mqtt/comp/memory_free"
    unit_of_measurement: "Мб"
    name: "Ноутбук оперативки свободно"
    
  - platform: mqtt
    state_topic: "mqtt/comp/disk_use"
    unit_of_measurement: "Гб"
    name: "Ноутбук на диске занято"
    
  - platform: mqtt
    state_topic: "mqtt/comp/disk_free"
    unit_of_measurement: "Гб"
    name: "Ноутбук на диске свободно"
 #### Банка ####   
  
  - platform: mqtt
    state_topic: "florarum"
    name: "Влажность воздуха в банке mqtt"
    unit_of_measurement: "%"
    value_template: "{{ value_json.hum }}"
    icon: mdi:water-percent
    
  - platform: mqtt
    state_topic: "florarum"
    name: "Температура воздуха в банке mqtt"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temp }}"
    icon: mdi:thermometer
    
  - platform: mqtt
    state_topic: "florarum"
    name: "Влажность почвы в банке mqtt"
    unit_of_measurement: "V"
    value_template: "{{ value_json.moisture }}"
    icon: mdi:water-sync